# Generated by Django 2.1.2 on 2018-10-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(default='6310 College Ave', max_length=200),
        ),
    ]
