# Generated by Django 2.1.2 on 2018-10-25 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_auto_20181025_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Ingredient'),
        ),
        migrations.AlterField(
            model_name='history',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.Store'),
        ),
    ]
