# Generated by Django 2.1.2 on 2018-10-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('quantity_num', models.IntegerField()),
                ('quantity_unit', models.CharField(max_length=200)),
            ],
        ),
    ]
